# Generated by Django 3.1.2 on 2020-10-18 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('total', models.FloatField()),
                ('peoples', models.IntegerField(default=1)),
                ('table_no', models.IntegerField(choices=[(1, 'Table 1'), (2, 'Table 2'), (3, 'Table 3')])),
                ('payment_method', models.CharField(choices=[('0', 'Cash'), ('1', 'Card'), ('2', 'UPI')], max_length=1)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_image/')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('0', 'Veg'), ('1', 'Non-veg')], max_length=1)),
                ('category', models.CharField(choices=[('0', 'Breakfast'), ('1', 'Lunch'), ('2', 'Snacks'), ('3', 'Dinner')], max_length=1)),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0)),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.product')),
            ],
        ),
    ]
