# Generated by Django 3.1.2 on 2020-10-24 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201024_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['table_no']},
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('0', 'Cash'), ('1', 'Card'), ('2', 'UPI')], default='0', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='table_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.table'),
        ),
        migrations.AddField(
            model_name='order',
            name='waiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.waiter'),
        ),
    ]
