# Generated by Django 3.1.2 on 2020-10-24 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201024_0932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waiter',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='waiter',
            name='email',
        ),
        migrations.RemoveField(
            model_name='waiter',
            name='phone',
        ),
    ]
