# Generated by Django 3.1.2 on 2020-10-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201024_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='fill',
            field=models.IntegerField(default=0, verbose_name='Fill'),
        ),
    ]
