# Generated by Django 3.1.2 on 2020-10-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_table_fill'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=8)),
                ('discount', models.IntegerField(default=0, verbose_name='Discount (%)')),
            ],
        ),
    ]
